### ISSUE TITLE
Filter by Relation.

### ISSUE THREAD

**Issue by hfmiguel** [lacodix/laravel-model-filter#47]
Hi, 

I take a look into :  https://www.lacodix.de/docs/laravel-model-filter/v1/advanced-usage/filter-relations

but i dont understand how uses well. 

Can you share another example ? 

For example , i have a list of users and users has Tags ( morphMany ) or ( belongsToMany ) relation . 

How can i filter all users with Tag 01, 02 etc ? I need to create a scope in Users model ? 

--------------

By the way , i write a trait to helper my filters to work with relations (all kind of relations ) .

```
trait FilterRelationTrait
{
    public function apply(Builder $query): Builder
    {
        return $query->whereHas($this->relation, function (Builder $query) {
            $query->whereIn($this->field, $this->values);
        });
    }
}
````

So , combining with a SelectFilter  , using the SelectInFilter , works like a charm to filter an model by relations values.

Example: 

TagsFilter.php 

- SelectInFilter : custom Filter to search using an array of values.
- FilterRelationTrait : trait to override the **apply** method to search by relations values.

```
class TagsFilter extends SelectInFilter
{
    use FilterRelationTrait;

    public FilterMode $mode = FilterMode::EQUAL;

    protected string $field = 'tag_id';  /**  column of the relation */ 
    protected string $relation = 'tags';  /** relation name : where the search will be applied */

    public function title(): string
    {
        return __('Tags');
    }

    public function component(): string
    {
        return 'select';
    }

    public function options(): array
    {
        return Tag::query()
            ->orderBy('name')
            ->pluck('id', 'name')
            ->toArray();
    }
}
```

FilterRelationTrait.php
```
trait FilterRelationTrait
{
    public function apply(Builder $query): Builder
    {
        return $query->whereHas($this->relation, function (Builder $query) {
            $query->whereIn($this->field, $this->values);
        });
    }
}
```

Result after search 

```
select * from `users` where exists (
  select * from `tags` inner join `taggables` on `tags`.`id` = `taggables`.`tag_id` where `users`.`id` = `taggables`.`taggable_id` and `taggables`.`taggable_type` = 'App\Models\Tenant\User' and `tag_id` in ('1', '2') and `tags`.`deleted_at` is null
)
 order by `name` asc limit 10 offset 0
```

**Comment by renky** [comment]
> How can i filter all users with Tag 01, 02 etc ? I need to create a scope in Users model ?

exactly, that's the idea behind... if you create a scope (even very complex ones) you can just use it in applyQuery-Functions of the filters... Don't think about a feature of this module - as statet at the top of the page this ideas base on "Eloquent Performance patterns" by Jonathan Reinink... It is just a thought-provoking impulse that you don't always need very complex Individual Filters with complex apply-Functions - sometimes you can simply create a good scope on your model and then just use one of the existing base filters...

---

Your relation filter is a problem that I'm currently also have... But not only with relations - also with simple "Selects" - in my case I'm offering all values that are available in a dedicated column (e.G. "type" - freetext of the user, and the Filter shall offer all already available values... so I'm requesting distinct values from database... 

I'll think about a base filter that will solve this things with only configuration instead of writing the same over and over again...

**Comment by renky** [comment]
@hfmiguel I added your examplt to the docs:

https://www.lacodix.de/docs/laravel-model-filter/v1/advanced-usage/filter-relations
i just combined the filter and the trait... 
I decided to NOT create a base filter from it... because I'd like to just give the "class" name to the filter and getting everyghing done automatically - but thats not so easy - you have to provide the relation name, the name-field and the class to be sure everything is working... so I think it is more explicit to create the filter like you did it...

and i moved my more complex example to the new page filter-relations-aggregations:
https://www.lacodix.de/docs/laravel-model-filter/v1/advanced-usage/filter-relations-aggregation

**Comment by hfmiguel** [comment]
Good,

Thanks for the feedback. I'll try updating the package in my next release to see.

Thank you
