### ISSUE TITLE
Reset individual or all filter

### ISSUE THREAD

**Issue by fadlisaad** [lacodix/laravel-model-filter#93]
Hi, is it possible to reset the filter individually, or the whole filter. I'm using the filterByQueryString method. Currently I've customized the layout to include the reset button, however I couldn't reset the filter.
![image](https://github.com/user-attachments/assets/275f7045-3423-49b9-9209-88fdb56db64c)

**Comment by renky** [comment]
Hi @fadlisaad 

for the whole filter-set you could simply add a <input type="reset"> to the form.
Finally it depends on your need - filterByQueryString just takes what the Url-Query puts in. Since I don't know how you currently bring your form-values to the query I can just guess.

If you only take the base blade-templates of me, it is a simple html-formt that must be submitted - in that case you just need to reset the value of the corresponding field via javascript when you klick on the reset button - so for example when Merchant is selected - you just need to unset the select-element via javascript (and ideally you submit the form imediatelly to update your results). So a small button with a clickhandler like that: 
onclick="document.getElementById('input_1').value = 'defaultvalue'; this.form.submit();"

if you want to reset all at once, just add a input type=reset button - that is basic html form functionality

In my current app I use Livewire for such things and i have customized all the templates to do a live-udpate. Finally I don't use the filterByQueryString method in that case - i just call filter manually.

To be honest - the UI is only a kind of a "how could it be done" in this package, because out there are so many solutions for creating your UI that eveything I create wouldn't fit in most cases...
